## NUMPY INTRODUCTION

#### What is NumPy

- NumPy is a Python library used for working with arrays.
- It also has functions for working in domain of linear algebra, fourier transform and matrices.
- NumPy was created in 2005 by Travis Oliphant, where it is an open source project and can be used freely.
- NumPy stands for Numerical Python

#### Why Use NumPy

- In Python we have lists that serve the purpose of arrays,but they are slow to process.
- NumPy aims to provide an array object that is upto 50x faster than Python lists.
- The array object is NumPy is called ndarray, it provides a lot of shopping functions that make working with ndarray very easy.
- Arrays are very frequently used in Data Science, where speed and resources are very important.

#### How NumPy is Faster than Lists

- Numpy arrays are stored at one continous place in memory unlike lists, so processes can access and manipulate them very efficiently.
- This behavior is called locality of reference in computer science.
- This is the main reason why NumPy is faster than lists.Also it is optimized to work with latest CPU architectures.

#### Note
- NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.
- The source code for NumPy is located at this github repository
https://github.com/numpy/numpy

### Installation of NumPy
- If you have Python and PIP alreay installed on a system, then install it using below command in jupyter notebook

In [2]:
# pip install numpy

In [5]:
#Importing the numpy
import numpy

arr = numpy.array([1,2,3,4,5,6])

# output in two ways
print(arr)
#or
arr

[1 2 3 4 5 6]


array([1, 2, 3, 4, 5, 6])

#### NumPy is usually imported under the np alias.

In [8]:
#Creating an alias with the as keyword while importing
import numpy as np

arr = np.array([1,2,3,4,5,6])

print(arr)

arr

[1 2 3 4 5 6]


array([1, 2, 3, 4, 5, 6])

### Checking NumPy Version

- The version string is stored under __version__ attribute.

In [9]:
import numpy as np
print(np.__version__)

1.19.5


# NumPy Creating Arrays 

## Creating a NumPy ndarray Object

- NumPy is used to work with arrays and the array object in NumPy is called ndarray.
- We can create a NumPy ndarray object by using the array() function.
- To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray.

In [12]:
#Using a list to create a NumPy array
import numpy as np
arr = np.array([1,2,3,4,5,6]) 

print(arr)

print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


> Note: type() - This built-in Python tells us the type of the object passed to it.Like in above code it shows that arr is numpy.ndarray type.

In [13]:
#Using a tuple to create a NumPy array
import numpy as np
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


## Dimensions in Arrays

- A dimension in arrays is one level of array depth(nested arrays).
- Nested arrays are arrays that have arrays as their elements.

### 0-D Arrays
- 0-D arrays, or Scalars are the elements in an array, Each value in an array is a 0-D array.

In [14]:
#Creating a 0-D array with value 42
import numpy as np
arr = np.array(42)
print(arr)

42


### 1-D Arrays
- An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array
- These are the most common and basic arrays

In [15]:
# Creating a 1-D array containing the values 1,2,3,4,5
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


### 2-D Arrays
- An array that has 1-D arrays as its elements is called a 2-D array.
- These are often used to represent matrix or 2nd order tensors.

In [16]:
#Creating a 2-D array containing two arrays with the values 1,2,3 and 6,7,8
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


### 3-D Arrays
- An array that has 2-D arrays(matrices) as its elements is called 3-D array.
- These are often used to represent a 3rd order tensor

In [17]:
# Create a 3-D array with two 2-D arrays both containing two arrays with the values 1,2,3 and 7,8,9
import numpy as np
arr = np.array([[[1,2,3],[7,8,9]], [[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]]]


## Checking the number of Dimensions  of the arrays

- NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [18]:
import numpy as np

a = np.array(56)
b = np.array([1,4,6,8,9])
c = np.array([[3,5,6],[2,9,20]])
d = np.array([[[2,4,5],[5,6,7]],[[12,5,8],[50,6,7]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### Higher Dimensional Arrays
- An array can have any number of dimensions.
- When the array is created, we can define the number of dimensions by using the ndim argument.

In [21]:
# Creating an array with 5 dimensions and verify that it has 5 dimensions.
import numpy as np
arr = np.array([1,2,3,4], ndmin=5)

print(arr)
print('numer of dimensions: ', arr.ndim)

[[[[[1 2 3 4]]]]]
numer of dimensions:  5


> In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array